// Расход красок Oikos из официальных технических листков (TDS).
// Ключи — CODE подпродукта из SUBPRODS.DBF.
// Значения: { kind: 'volume'|'mass', yield: [min,max] m²/(L|kg) на одну установку из coats слоёв,
//             coats: типичное число слоёв, source: ссылка на TDS, notes: '...' }
// Если расхода нет — пользователь вводит площадь, но получает только напоминание заглянуть в TDS.

window.OIKOS_COVERAGE = {
  // INTERIOR
  "CM":      { kind: "volume", yield: [4, 5],     coats: 2, source: "INT/CX/02 (Coprimax)",      notes: "новая штукатурка" },
  "EN":      { kind: "volume", yield: [6, 8],     coats: 1, source: "INT/EN/02 (Encanto)",       notes: "1 слой кистью; в 2 слоя × 20% воды" },
  "KR":      { kind: "volume", yield: [1, 2],     coats: 2, source: "INT/KR/07 (Kreos)",         notes: "тонкослойная декоративная штукатурка" },
  "BI3":     { kind: "volume", yield: [4, 4.5],   coats: 1, source: "INT/BX/01 (Biamax 03)",     notes: "Effetto Anticato" },
  "BI7":     { kind: "volume", yield: [1.2, 1.2], coats: 2, source: "INT/BX/01 (Biamax 07)",     notes: "Effetto Intonaco; для Anticato 3.5-4 м²/л в 1 слой" },
  "MM":      { kind: "mass",   yield: [0.5, 0.5], coats: 2, source: "EXT/mn/07 (Marmorino Naturale)", notes: "2 кг/м² в 2 слоя" },
  "MMF":     { kind: "mass",   yield: [0.55, 0.6], coats: 2, source: "Marmorino Naturale Fine",   notes: "≈2 кг/м² в 2 слоя; на гладких до 1.7 м²/кг" },
  "MDE":     { kind: "volume", yield: [5, 8],     coats: 1, source: "INT/ME/02 (Multidecor E)",  notes: "зависит от техники" },
  "MDO":     { kind: "volume", yield: [5, 8],     coats: 1, source: "INT/ME/02 (Multidecor E Opac)", notes: "" },
  "MDS":     { kind: "volume", yield: [5, 8],     coats: 1, source: "INT/ME/02 (Multidecor ES)", notes: "" },
  "SKIN":    { kind: "volume", yield: [5, 8],     coats: 1, source: "INT/me/skin (Multidecor Skin)", notes: "" },
  "EX2019":  { kind: "volume", yield: [10, 12],   coats: 2, source: "Extrapaint",                notes: "укрывистая, как SUPERCOLOR" },
  "EXOLD":   { kind: "volume", yield: [10, 12],   coats: 2, source: "Extrapaint Old",            notes: "" },
  "FF":      { kind: "volume", yield: [40, 60],   coats: 1, source: "Finitura Autolucidante",    notes: "тонкослойный финишный лак" },
  "II":      { kind: "mass",   yield: [0.4, 0.5], coats: 2, source: "Intonaco Antico",           notes: "≈2-2.5 кг/м²" },
  "FLEXIGRAP":{kind: "volume", yield: [1.5, 2],   coats: 2, source: "Flexigrap",                 notes: "эластомерное покрытие, толстое" },
  "FLEXLIS": { kind: "volume", yield: [4, 6],     coats: 2, source: "Flexigrap Liscio",          notes: "гладкая версия" },
  "STERYLCALCE":{kind:"mass",  yield: [0.4, 0.5], coats: 2, source: "Sterilcalce",               notes: "санирующая известковая штукатурка" },
  "FDOLD":   { kind: "volume", yield: [10, 12],   coats: 2, source: "Fondo Murales",             notes: "белая основа" },
  "SCOLD":   { kind: "volume", yield: [7, 10],    coats: 2, source: "Supercolor",                notes: "INT/SC/02: 7-15 м²/л" },
  "WALLSATIN":{kind: "volume", yield: [10, 12],   coats: 2, source: "Wallsatin",                 notes: "" },
  "SUPERMATT":{kind: "volume", yield: [9, 11],    coats: 2, source: "Supermatt",                 notes: "" },
  "TOPMATT": { kind: "volume", yield: [9, 11],    coats: 2, source: "Topmatt",                   notes: "" },
  "USL":     { kind: "volume", yield: [10, 12],   coats: 2, source: "Ultrasaten Lucido",         notes: "" },
  "USO":     { kind: "volume", yield: [10, 12],   coats: 2, source: "Ultrasaten Opaco",          notes: "" },
  "USS":     { kind: "volume", yield: [10, 12],   coats: 2, source: "Ultrasaten Satinato",       notes: "" },
  "NEC":     { kind: "volume", yield: [9, 11],    coats: 2, source: "Neoclassica",               notes: "" },
  "ECOSHABBY":{kind:"volume",  yield: [8, 10],    coats: 2, source: "Ecoshabby",                 notes: "" },
  "CPV":     { kind: "volume", yield: [4, 5],     coats: 2, source: "Coprimax variant",          notes: "" },

  // EXTERIOR (PROD0002)
  "AR":      { kind: "volume", yield: [7, 9],     coats: 2, source: "Architall",                 notes: "" },
  "BG":      { kind: "volume", yield: [1, 1.5],   coats: 2, source: "Betoncryll Pigmentato",     notes: "" },
  "BS":      { kind: "volume", yield: [4, 5],     coats: 2, source: "Betoncryll Semitrasparente",notes: "" },
  "BIO":     { kind: "volume", yield: [4, 6],     coats: 2, source: "Biocompact",                notes: "силиконовая фасадная" },
  "BIO ELA": { kind: "volume", yield: [3, 5],     coats: 2, source: "Biocompact Elastic",        notes: "эластичная" },
  "BK":      { kind: "volume", yield: [9, 11],    coats: 2, source: "Blankor",                   notes: "" },
  "DUAFLEX": { kind: "volume", yield: [3, 5],     coats: 2, source: "Duaflex 03/07",             notes: "" },
  "DB":      { kind: "mass",   yield: [0.5, 0.7], coats: 2, source: "Decorsil Bologna",          notes: "≈1.5-2 кг/м²" },
  "DBF":     { kind: "mass",   yield: [0.6, 0.8], coats: 2, source: "Decorsil Bologna Fine",     notes: "" },
  "DF":      { kind: "mass",   yield: [0.5, 0.7], coats: 2, source: "Decorsil Firenze",          notes: "" },
  "DR":      { kind: "mass",   yield: [0.5, 0.7], coats: 2, source: "Decorsil Roma",             notes: "" },
  "DV":      { kind: "mass",   yield: [0.5, 0.7], coats: 2, source: "Decorsil Venezia",          notes: "" },
  "DPP":     { kind: "volume", yield: [3, 5],     coats: 1, source: "Decorsil Primer Pigmentato",notes: "грунт" },
  "EG":      { kind: "volume", yield: [1.5, 2.5], coats: 2, source: "Elastrong Gum",             notes: "" },
  "EP":      { kind: "volume", yield: [1.5, 2.5], coats: 2, source: "Elastrong Paint Gum",       notes: "" },
  "ET":      { kind: "volume", yield: [3, 5],     coats: 2, source: "Elastrong Venezia",         notes: "" },
  "EV":      { kind: "volume", yield: [4, 6],     coats: 2, source: "Elastrong Venezia Fine",    notes: "" },
  "FLEXIGRAP_EXT":{kind:"volume",yield:[1.5, 2],  coats: 2, source: "Flexigrap external",        notes: "" },
  "PITTURA": { kind: "volume", yield: [8, 10],    coats: 2, source: "Pittura per esterni",       notes: "" },
};
